// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#include "Assets/Shaders/Includes/Simplex.cginc"

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture3D<float4> Result;

int seed;

uint width;
uint height;
uint depth;

int octaves;

float amplitude;
float persistance;
float lacunarity;
float frequency;

//float domainWarp;

//bool absValue;


void setSeedPRNG(int seed)
{
    startSeed = seed;
}

float CalcPixel3D(float3 pos, float scale)
{
    float value = Generate(pos.x * scale, pos.y * scale, pos.z * scale) * 128 + 128;
    value /= 255;
    value -= 0.5f;
    value *= 2;
    return value;
}

void CalculateTexture(uint3 id){
    uint xOver64 = width / 64;
    uint xPerThread = xOver64 * id.x;
    uint XstartIndex = id.x * (xOver64);
    uint XendIndex = XstartIndex + (xOver64);

    uint yOver64 = height / 64;
    uint yPerThread = yOver64 * id.y;
    uint YstartIndex = id.y * (yOver64);
    uint YendIndex = YstartIndex + (yOver64);

    uint zOver64 = depth / 64;
    uint zPerThread = zOver64 * id.z;
    uint ZstartIndex = id.z * (zOver64);
    uint ZendIndex = ZstartIndex + (zOver64);

    period = width/2;
    float3 offset = float3(10000,10000,10000);

    float baseFreq = frequency / (float)width;
    for(uint i = XstartIndex; i < XendIndex; ++i){
        for(uint j = YstartIndex; j < YendIndex; ++j){
            for(uint k = ZstartIndex; k < ZendIndex; ++k){
                float f = baseFreq;
                float a = amplitude;
                float total = 0;
                float3 pos = float3(i ,j ,k );
                for(uint o = 0; o < octaves; ++o){
                    
                    
                    total += CalcPixel3D(pos + offset,f) * a;
                    f *= lacunarity;
                    a *= persistance;
                }
                Result[pos] = total;
            }
        }
    }
}

[numthreads(8, 8, 8)]
void CSMain(uint3 id : SV_DispatchThreadID)
{

    if (seed != 0)
    {
        setSeedPRNG(seed);
        resetLookUpTable();
        
    }


    CalculateTexture(id);

    /*
    float result = 0;
    float amplitude = 1;
    
    
    //would we want to calculate the vertices in here? it may be easier to apply the colors with the dot product that way
    //we would need separate shaders regardless since vertices can't talk to each other
    //pass 1 : get noise result
    //pass 2 : pass in normals and distance from planet origin and assign color
    //pass 3 : flat shading
    
    //so, pass in color regions and heights into planet shader and assign according
    
    for (int i = 0; i < octaves; ++i)
    {
        float3 pos = 
        result += (CalcPixel3D(vertexPos + displace, frequency)) * amplitude;
        amplitude *= persistance;
        frequency *= lacunarity;
    }

    result = (absValue) ? (1 - (abs(result))) : result;
    Result[id.xy] += result;
    */
    }
