using System;
using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;


namespace worley_3d {
    public class Worley3D
    {
        private Vector3 origin;
        private List<Vector3> points;
        private int size;
        private float pointResolution;

        //CONSTRUCTOR TO INITIALIZE VALUES
        public Worley3D(ref List<Vector3> worleyPoints, Vector3 _origin,int resolution,int pointRes) {
            points = new List<Vector3>();
            origin = _origin;
            size = resolution;
            pointResolution = pointRes;
        }

        private void generateWorleyPoints(Vector3 index)
        {
            //Vector3 point = new Vector3(UnityEngine.Random.Range(-100, 100), UnityEngine.Random.Range(-100, 100), UnityEngine.Random.Range(-100, 100));
            Vector3 point = origin + new Vector3(index.x / size - 0.5f, index.y / size - 0.5f, index.z / size - 0.5f);

            point += (Vector3.one * (1.0f / size))+(new Vector3(UnityEngine.Random.Range(-1,1f), UnityEngine.Random.Range(-1, 1f), UnityEngine.Random.Range(-1, 1f))/size);
            point += new Vector3(1f / size * 0.5f, 1f / size * 0.5f, 1f / size * 0.5f);

            points.Add(point);
        }

        private float FindClosestPoint(Vector3 index)
        {

            float closestDistance = float.MaxValue;
            float distance;
            Vector3 point = origin + new Vector3(index.x / size - 0.5f, index.y / size - 0.5f, index.z / size - 0.5f);

            for (int i = 0; i < points.Count; ++i)
            {

                distance = Vector3.Distance(points[i], point);
                if (distance < closestDistance) closestDistance = distance;
            }
            return closestDistance;
        }


        [MenuItem("CreateExamples/3DTexture")]
        public void CreateTexture3D()
        {
            //takes in the worley points generated by the planet script.

            //worley points are in world position
            int octaves = 4;
            float persistence = 1;


            // Configure the texture
            int size = 32;
            TextureFormat format = TextureFormat.RFloat;
            TextureWrapMode wrapMode = TextureWrapMode.Repeat;

            // Create the texture and apply the configuration
            Texture3D texture = new Texture3D(size, size, size, format, false);
            texture.wrapMode = wrapMode;

            // Create a 3-dimensional array to store color data
            Color[] colors = new Color[size * size * size];

            for (int i = 0; i < octaves; ++i)
            {
                points = new List<Vector3>();
                //create array of worley points proportional to the size of the area
                for (int z = 0; z < pointResolution; z++)
                {
                    int zOffset = z * (size / 8) * (size / 8);
                    for (int y = 0; y < pointResolution; y++)
                    {
                        int yOffset = y * (size / 8);
                        for (int x = 0; x < pointResolution; x++)
                        {
                            //This matches the position of each point to the image coords. Figures out how many indices to skip
                            float pointCoordScalar = size / pointResolution;
                            Vector3 index = new Vector3(x, y, z) * pointCoordScalar;
                            generateWorleyPoints(index);
                        }
                    }
                }

                // Populate the array so that the x, y, and z values of the texture will map to red, blue, and green colors
                float inverseResolution = 1.0f / (size - 1.0f);
                for (int z = 0; z < size; z++)
                {
                    int zOffset = z * size * size;
                    for (int y = 0; y < size; y++)
                    {
                        int yOffset = y * size;
                        for (int x = 0; x < size; x++)
                        {
                            Vector3 index = new Vector3(x, y, z);
                            float scalar = FindClosestPoint(index);
                            if (i == 0) colors[x + yOffset + zOffset] = new Color(1, 1, 1, 1);
                            colors[x + yOffset + zOffset] -= (new Color(1, 1, 1, 1) * scalar*persistence);
                        }
                    }
                }
                pointResolution *= 0.75f ;
                persistence *= 0.5f;
            }

            // Copy the color values to the texture
            texture.SetPixels(colors);

            // Apply the changes to the texture and upload the updated texture to the GPU
            texture.Apply();

            // Save the texture to your Unity Project
            AssetDatabase.CreateAsset(texture, "Assets/Example3DWorleyTexture.asset");
        }

      
    }
}
