// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#include "Assets/Shaders/Includes/Math.cginc"
#include "Assets/Shaders/Includes/SDF.cginc"

struct SVONode{
    float3 position;
    float size;
    float min, max;
    int edge;
    float3 vertex;
    int materialIndex;
};


Texture3D<float4> ContinentTexture;
SamplerState samplerContinentTexture;

Texture3D<float4> MountainTexture;
SamplerState samplerMountainTexture;

Texture3D<float4> OctaveTexture;
SamplerState samplerOctaveTexture;

uint width, height, depth;

RWStructuredBuffer<SVONode> nodes;
uint nodeLimit;

RWStructuredBuffer<SDF> sdfs; //these should be hashed, someway, somehow
uint sdfLimit;


// axis bit constants used throughout the method
const int X_AXIS = 4;
const int Y_AXIS = 2;
const int Z_AXIS = 1;

//float min and max values
const float MAX = 3.402823466e+38;
const float MIN = 1.175494351e-38;

//planet data
float radius;


float2 DetermineSDFValue(float3 pos, float size){ //returns the value and material index
    float3 sphereCenter = float3(1,1,1) * radius;
    float3 spherePos = pos - sphereCenter;

    float sphereSDF = length(spherePos) - radius * 0.8;
    float frequency = .05;
    float amplitude = 50.0;
    spherePos /= width; //even dimensions

    //In the future, this continent value will be baked into the actual texture
    float3 uvwContinent = (pos * (0.5/radius));
    float contVal = (ContinentTexture.SampleLevel(samplerContinentTexture, uvwContinent, 0)).r;

    float mountainVal = (MountainTexture.SampleLevel(samplerMountainTexture, uvwContinent, 0)).r;
    mountainVal = (1.0 - (mountainVal < 0 ? -mountainVal : mountainVal));

    float octaveVal = (OctaveTexture.SampleLevel(samplerMountainTexture, uvwContinent, 0)).r;
    //-------------------------------------------------------------------------

    float value = sphereSDF - (contVal*50 + max(0,contVal) * mountainVal*100 + octaveVal*50);

    int materialIndex = (contVal+octaveVal) > 0 && value > -2 ? 0 : 1; // just for simplicity
    materialIndex = mountainVal > 0.5 && contVal > 0 ? 2 : materialIndex;
    
    for(uint i = 1; i < sdfLimit; ++i){
        if(sdfs[i].invert == 0){
            value = max(value, -EvaluateSDF(pos,sdfs[i]));
        }else{
            value = min(value, EvaluateSDF(pos,sdfs[i]));
        }
        
    }

    return float2(value,materialIndex);
}

float Adapt(float x0, float x1) { 
    float denominator = x1-x0;
    return abs(denominator) < 1e-8 ? 0.5 : (-x0) / (x1 - x0);
}

void SVOVertex(SVONode node, int index)
{
    //these are being allocated every frame, which is bad
    const float eps = 1e-9f;

    float xPos, yPos, zPos;
    float minSDF = MAX, maxSDF = -MAX;
    float2 sdfmaterial;

    float3 vertPos[8];
    float vertValues[8];
    float avgValue = 0;

    int i = 0;
    for (; i < 8; ++i)
    {
        //eulerian coordinate grid at resolution node.size
        xPos = node.position.x + ((i >> 2) & 0x01) * node.size;
        yPos = node.position.y + ((i >> 1) & 0x01) * node.size;
        zPos = node.position.z + (i & 0x01) * node.size;

        //evaluate the position and value of each vertex in the unit cube
        vertPos[i] = float3(xPos, yPos, zPos);
        sdfmaterial = DetermineSDFValue(vertPos[i], node.size);

        vertValues[i] = sdfmaterial.x; //base SDF
        if(i==0)node.materialIndex = sdfmaterial.y;
        maxSDF = vertValues[i] > maxSDF ? vertValues[i] : maxSDF;
        minSDF = vertValues[i] < minSDF ? vertValues[i] : minSDF;
    }
    //calculate the adapt of only the edges that cross, rather than the whole thing
    //calculate the positions of the edges itself
    node.min = minSDF;
    node.max = maxSDF;
    node.edge = -1;
    node.vertex = float3(0,0,0);

    float3 avg = float3(0,0,0);
    int count = 0;

    //replace Vector3 with dynamic sizing

    //we then identify where changes in the function are (sign changes)
    bool signChange = false;
    bool xCross;
    bool yCross;
    bool zCross;

    //set sign change if any edge is crossed
    signChange = signChange || ((vertValues[0] > eps) != (vertValues[4] > eps));
    signChange = signChange || (vertValues[0] > eps) != (vertValues[1] > eps);
    signChange = signChange || (vertValues[5] > eps) != (vertValues[1] > eps);
    signChange = signChange || (vertValues[5] > eps) != (vertValues[4] > eps);
    signChange = signChange || (vertValues[4] > eps) != (vertValues[6] > eps);
    signChange = signChange || (vertValues[1] > eps) != (vertValues[3] > eps);
    signChange = signChange || (vertValues[0] > eps) != (vertValues[2] > eps);
    yCross = (vertValues[5] > eps) != (vertValues[7] > eps);
    zCross = (vertValues[6] > eps) != (vertValues[7] > eps);
    xCross = (vertValues[3] > eps) != (vertValues[7] > eps);
    signChange = signChange || yCross;
    signChange = signChange || zCross;
    signChange = signChange || xCross;
    signChange = signChange || (vertValues[2] > eps) != (vertValues[3] > eps);
    signChange = signChange || (vertValues[2] > eps) != (vertValues[6] > eps);

    if (!signChange) {
        nodes[index] = node;
        return;
    }

    //X EDGES NEW 
    for (i = 0; i < 4; ++i)
    {
        float a = vertValues[i];
        float b = vertValues[i | 0x04];
        if (a > 0 != b > 0)
        {
            avg += vertPos[i] + Adapt(a, b) * (vertPos[i | 0x04] - vertPos[i]);
            count++;
        }
    }

    //Y EDGES
    int j = 0;
    for (i = 0; i < 4; ++i)
    {

        if (i < 2)
        {
            j = i;
        }
        else
        {
            j = i == 2 ? 4 : 5;
        }
        float a = vertValues[j];
        float b = vertValues[j | 0x02];
        if (a > eps != b > eps)
        {
            avg += vertPos[j] + Adapt(a, b) * (vertPos[j | 0x02] - vertPos[j]);
            count++;
        }
    }

    //Z EDGES
    for (i = 0; i < 4; ++i)
    {
        float a = vertValues[(i << 1)];
        float b = vertValues[(i << 1) | 0x01];
        if (a > eps != b > eps)
        {
            avg += vertPos[i << 1] + Adapt(a, b) * (vertPos[(i << 1) | 0x01] - vertPos[i << 1]);
            count++;
        }
    }
    if (count == 0) {
        nodes[index] = node;
        return;
    }

    avg /= max(count,1);
    //convert the average position to a sphere

    //figure out what edge was crossed (axis)

    //Assign the sign of the edge according to how the flip occurs

    //The normals shouldn't have x,y,z as their parameters, but should instead reflect
    //the positions of the intermediate point on the edge.

    int newedge = 0;

    if (xCross)
    {
        newedge |= 1 << 5;
        newedge |= (((vertValues[3] > eps) && !(vertValues[7] > eps)) ? 1 : 0) << 2;
    }
    if (yCross)
    {
        newedge |= 1 << 4;
        newedge |= ((!(vertValues[5] > eps) && (vertValues[7] > eps)) ? 1 : 0) << 1;
    }
    if (zCross)
    {
        newedge |= 1 << 3;
        newedge |= ((vertValues[6] > eps) && !(vertValues[7] > eps)) ? 1 : 0;
    }

    bool block_voxel = false;
    float3 vertex = block_voxel ? vertPos[0] : avg;


    node.vertex = vertex;
    node.edge = newedge;

    nodes[index] = node;
}

void CalculateVertex(int id){
    uint nodesOver64 = nodeLimit / 64;
    uint nodesPerThread = nodesOver64 * id;
    uint startIndex = id * (nodesOver64);
    uint endIndex = startIndex + (nodesOver64);

    for(uint i = startIndex; i < endIndex; ++i){
        SVOVertex(nodes[i], i);
    }
} 

[numthreads(64,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    
    ContinentTexture.GetDimensions(width, height, depth);
    // TODO: insert actual code here!
    CalculateVertex(id.x);
}
